<a href="https://colab.research.google.com/github/pro-jain/Trend-Swipe-Yah-or-Nah/blob/main/8_2_RL_example_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reinfocement Learning  Example :PathFinder Bot

Suppose we have 5 rooms A to E, in a building connected by certain doors :
We  can  consider  outside  of  the  building  as  one  big  room  say  F  to  cover the building.
There are two doors lead to the building from F, that is through room B and room E.


![title](RL_problem.png)

Which path agent should choose???



# Step 1: Modeling the environment-

- Represent the rooms by graph,
- Each room as a vertex (or node) and
- Each door as an edge (or link).
- Goal room is the node F
![image.png](RL1.png)




Goal :  Outside the building : Node F
Assign Reward Value to each room  

State:  Each room (including outside building )

Action : Agent’s Movement from 1 room to next room

Initial state : C (random )

Reward: Goal Node :highest reward (100)  rest – 0;

State Diagram
![image.png](RL2.png)


![title](RL_image.png)

In [1]:
import numpy as np

In [4]:
# R matrix

Rewards = np.matrix([
    [0,0,0,0,-1,1],[0,0,0,0,0,1],[0,0,0,0,0,0],[0,-1,-1,0,0,1],[0,0,0,-1,0,1],[0,0,0,0,0,0]
                     ])

Rewards

matrix([[ 0,  0,  0,  0, -1,  1],
        [ 0,  0,  0,  0,  0,  1],
        [ 0,  0,  0,  0,  0,  0],
        [ 0, -1, -1,  0,  0,  1],
        [ 0,  0,  0, -1,  0,  1],
        [ 0,  0,  0,  0,  0,  0]])

In [5]:
# Q matrix: zero matrix  of size same as R matrix

Q = np.matrix(np.zeros([6,6]))
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [6]:
# Gamma (learning parameter).
gamma = 0.8

In [7]:
# Initial state. (Usually to be chosen at random)
initial_state = 1

# Write your Code to choose random State

In [8]:
# This function returns all available actions in the state given as an argument
def available_actions(state):
    current_state_row = Rewards[state,]
    av_act = np.where(current_state_row >= 0)[1]
    return av_act

In [9]:
# Get available actions in the current state
available_act = available_actions(initial_state)

In [10]:
# This function chooses at random which action to be performed within the range
# of all the available actions.
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act,1))
    return next_action

In [11]:
# Sample next action to be performed
action = sample_next_action(available_act)

<ipython-input-10-b40dc4f18bf8>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  next_action = int(np.random.choice(available_act,1))


In [13]:
# This function updates the Q matrix according to the path selected and the Q
# learning algorithm
def update(current_state, action, gamma):

    max_index = np.where(Q[action,] == np.max(Q[action,]))[1]

    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size = 1))
    else:
        max_index = int(max_index)
    max_value = Q[action, max_index]

    # Q learning formula
    Q[current_state, action] = Rewards[current_state, action] + gamma * max_value

# Update Q matrix
update(initial_state,action,gamma)

<ipython-input-13-15ea1a1dcf4c>:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  max_index = int(np.random.choice(max_index, size = 1))


In [14]:
def sample_next_action(available_act, epsilon=0.1):
    if np.random.rand() < epsilon:  # Exploration
        action = np.random.choice(available_act)
    else:  # Exploitation
        q_values = [Q[available_act[i], available_act[i]] for i in range(len(available_act))]
        action = available_act[np.argmax(q_values)]
    return action

# Train over 10,000 iterations
for i in range(10000):
    current_state = np.random.randint(0, int(Q.shape[0]))  # Randomly pick a state
    available_act = available_actions(current_state)  # Get available actions for the current state
    action = sample_next_action(available_act)  # Pick the next action based on epsilon-greedy
    score = update(current_state, action, gamma)  # Update Q matrix with the chosen action

# The "trained" Q matrix
print("The Trained Q matrix:")
print(Q)

# Normalize the "trained" Q matrix
print("Trained Normalized Q matrix:")
Q_nor = (Q - np.min(Q)) / (np.max(Q) - np.min(Q))  # Min-Max normalization
print(Q_nor)


<ipython-input-13-15ea1a1dcf4c>:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  max_index = int(np.random.choice(max_index, size = 1))
<ipython-input-13-15ea1a1dcf4c>:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  max_index = int(max_index)


The Trained Q matrix:
[[2.22222222 2.22222222 1.77777778 2.22222222 0.         2.77777778]
 [2.22222222 2.22222222 1.77777778 2.22222222 2.22222222 2.77777778]
 [2.22222222 2.22222222 1.77777778 2.22222222 2.22222222 1.77777778]
 [2.22222222 0.         0.         2.22222222 2.22222222 2.77777778]
 [2.22222222 2.22222222 1.77777778 0.         2.22222222 2.77777778]
 [2.22222222 2.22222222 1.77777778 2.22222222 2.22222222 1.77777778]]
Trained Normalized Q matrix:
[[0.8  0.8  0.64 0.8  0.   1.  ]
 [0.8  0.8  0.64 0.8  0.8  1.  ]
 [0.8  0.8  0.64 0.8  0.8  0.64]
 [0.8  0.   0.   0.8  0.8  1.  ]
 [0.8  0.8  0.64 0.   0.8  1.  ]
 [0.8  0.8  0.64 0.8  0.8  0.64]]


In [15]:
#-------------------------------------------------------------------------------
# Testing

#STATES = [A,B,C,D,E,F]
#nO_State=[0,1,2,3,4,5]

# Goal state = 5
# Best sequence path starting from 2 -> 2, 3, 1, 5

current_state = 2
steps = [current_state]

while current_state != 5:

    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]

    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size = 1))
    else:
        next_step_index = int(next_step_index)

    steps.append(next_step_index)
    current_state = next_step_index

<ipython-input-15-b473c09bc87c>:20: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  next_step_index = int(next_step_index)


In [16]:
# Print selected sequence of steps
print("Selected path:")

# Start from a random state
current_state = np.random.randint(0, int(Q.shape[0]))

# Initialize a list to store the selected path
path = [current_state]

# Define a limit for the number of steps (you can set this as needed)
step_limit = 10

for _ in range(step_limit):
    # Choose the best action based on the current Q values (greedy choice)
    available_act = available_actions(current_state)

    # Choose the action with the highest Q-value
    action = available_act[np.argmax([Q[current_state, act] for act in available_act])]

    # Move to the next state based on the chosen action
    current_state = action

    # Add the current state to the path
    path.append(current_state)

# Print the sequence of states (path)
print(path)


Selected path:
[4, np.int64(5), np.int64(3), np.int64(5), np.int64(3), np.int64(5), np.int64(3), np.int64(5), np.int64(3), np.int64(5), np.int64(3)]


![image.png](RL_prob.png)
